# Generated by Django 5.2.1 on 2025-05-27 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
