# Generated by Django 5.2.1 on 2025-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0003_contact_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
