# Generated by Django 5.2.1 on 2025-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0004_alter_contact_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="service",
            field=models.CharField(max_length=50),
        ),
    ]
