# Generated by Django 5.2.1 on 2025-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0005_alter_contact_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, default="2020-06-25"),
            preserve_default=False,
        ),
    ]
