# Generated by Django 5.2.1 on 2025-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electricians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='media/')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=5)),
                ('service_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='media/')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=5)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
