# Generated by Django 5.2.1 on 2025-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricians',
            name='service_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='plumbers',
            name='service_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
