# Generated by Django 5.2.1 on 2025-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_electricians_service_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=5)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
