# Generated by Django 5.2.1 on 2025-06-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_plumbing_service_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="smartTv_service_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_name", models.CharField(max_length=50)),
                ("booking_email", models.EmailField(max_length=254)),
                ("booking_phone", models.CharField(max_length=10)),
                ("booking_location", models.CharField(max_length=50)),
                ("booking_service", models.CharField(max_length=50)),
                ("booking_price", models.CharField(max_length=5)),
                ("booking_address", models.TextField()),
            ],
        ),
    ]
