# Generated by Django 5.2.1 on 2025-06-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_smarttv_service_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="electrical_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="plumbing_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="smarttv_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
