# Generated by Django 5.2.1 on 2025-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_electrical_service_booking_date_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electrical_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, default="2020-04-06"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plumbing_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, default="2020-04-06"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="smarttv_service_booking",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, default="2020-04-06"),
            preserve_default=False,
        ),
    ]
