# Generated by Django 5.2.1 on 2025-07-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_electrical_service_booking_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Electric_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.CharField(max_length=5)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
