# Generated by Django 5.2.1 on 2025-07-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_book_electric_station'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Electric_Station',
            new_name='Electric_Station',
        ),
    ]
