# Generated by Django 5.2.1 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_book_electric_station_electric_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Charging_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_name', models.CharField(max_length=100)),
                ('Station_address', models.TextField()),
                ('Station_location', models.CharField(max_length=100)),
                ('Station_price', models.IntegerField()),
                ('Station_number', models.IntegerField(max_length=10)),
                ('Station_status', models.BooleanField()),
            ],
        ),
    ]
