# Generated by Django 5.2.1 on 2025-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_add_charging_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_charging_station',
            name='Station_img',
            field=models.ImageField(default='2019-06-05', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_charging_station',
            name='Station_number',
            field=models.IntegerField(),
        ),
    ]
