# Generated by Django 5.2.1 on 2025-08-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_add_charging_station_station_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_charging_station',
            name='Station_number',
        ),
        migrations.AlterField(
            model_name='add_charging_station',
            name='Station_location',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='add_charging_station',
            name='Station_status',
            field=models.BooleanField(default=True),
        ),
    ]
