# Generated by Django 5.2.1 on 2025-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_add_charging_station_station_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charging_station_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=50)),
                ('booking_email', models.EmailField(max_length=254)),
                ('booking_phone_no', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=50)),
                ('station_location', models.URLField()),
                ('station_price', models.CharField(max_length=4)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Electric_Station',
        ),
    ]
