# Generated by Django 5.2.1 on 2025-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_charging_station_booking_delete_electric_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_charging_station',
            name='Station_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
