# Generated by Django 5.2.1 on 2025-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_add_charging_station_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_charging_station',
            name='Station_status',
            field=models.CharField(max_length=10),
        ),
    ]
